version: '3.4'
services:

  cron:
      image: jfernancordova/elasticsearch-crons:1.0.0
      environment:
        CRON_ENTRY: "* * * * * curl http://php/api/zohoSync/Contacts"
        CRON_ENTRY: "* * * * * curl http://php/api/zohoSync/Leads"
        CRON_ENTRY: "* * * * * curl http://php/api/zohoSync/Potentials"
        CRON_ENTRY: "* * * * * curl http://php/api/zohoSync/Accounts"
      depends_on:
        - php
      deploy:
        mode: replicated
        replicas: 1
  php:
    image: jfernancordova/docker-laravel-api-dev
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
    ports:
     - "80:80"
    volumes:
     - .:/docker-laravel-api-dev
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: apiLaravelDocker
      MYSQL_USER: apiLaravelDocker
      MYSQL_PASSWORD: apiLaravelDocker
      MYSQL_ROOT_PASSWORD: apiLaravelDocker
    volumes:
      - .docker/local-mysql-datadir:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
